apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: {{ .Values.nodePort }}
      protocol: TCP