apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      containers:
        - name: argocd-server
          command: ["argocd-server"]
          args: ["--insecure"]